from tools import fetch_ai_news
from summarize import (
    classify_india_ai_batch,
    summarize_article,
    score_news_impact
)
from email_sender import send_email
from llm_monitor import print_summary, log_to_file
from datetime import date


def run_news_agent():

    print("Starting AI News Agent...")

    articles = fetch_ai_news()

    if not articles:
        print("No articles fetched")
        return

    titles = [a["title"] for a in articles]

    # Step 1 — Batch classification
    relevant_indices = classify_india_ai_batch(titles)

    relevant_articles = [articles[i] for i in relevant_indices]

    scored_articles = []

    # Step 2 — Impact scoring
    for art in relevant_articles:

        score = score_news_impact(art["title"])
        art["impact_score"] = score

        scored_articles.append(art)

    # Step 3 — Rank by importance
    scored_articles = sorted(
        scored_articles,
        key=lambda x: x["impact_score"],
        reverse=True
    )

    top_articles = scored_articles[:5]

    today = date.today().strftime("%B %d, %Y")

    # HTML Email Start
    report = f"""
    <html>
    <head>
    <style>

    body {{
        font-family: Arial, sans-serif;
        background-color: #f4f6f8;
    }}

    .container {{
        max-width: 800px;
        margin: auto;
    }}

    .header {{
        background-color: #1f4e79;
        color: white;
        padding: 15px;
        text-align: center;
        border-radius: 6px;
    }}

    .date {{
        text-align:center;
        margin-top:5px;
        color:#666;
    }}

    .news-card {{
        background: white;
        padding: 15px;
        margin-top: 15px;
        border-radius: 6px;
        border-left: 6px solid #1f77b4;
    }}

    .headline {{
        font-size: 18px;
        font-weight: bold;
        color: #1f77b4;
    }}

    .score {{
        float:right;
        background:#ffcc00;
        padding:4px 8px;
        border-radius:4px;
        font-weight:bold;
    }}

    .source {{
        margin-top:10px;
        font-size:13px;
    }}

    </style>
    </head>

    <body>

    <div class="container">

    <div class="header">
    <h2>AI Developments in India – Daily Brief</h2>
    </div>

    <div class="date">{today}</div>
    """

    # Add each news card
    for art in top_articles:

        summary = summarize_article(art["title"])

        summary = summary.replace("Headline:", "<b>Headline:</b><br>")
        summary = summary.replace("Key Points:", "<br><b>Key Points:</b>")
        summary = summary.replace("Impact:", "<br><b>Impact:</b><br>")

        report += f"""

        <div class="news-card">

        <div style="font-size:18px;font-weight:bold;color:#1f77b4;">
        <a href="{art['link']}" style="color:#1f77b4;text-decoration:none;">
        {art['title']}
        </a>
        <span style="float:right;background:#ffcc00;padding:4px 8px;border-radius:4px;font-weight:bold;">
        Impact {art['impact_score']}
        </span>
        </div>

        <div>
        {summary}
        </div>

        <div class="source">
        Source: <a href="{art['link']}">{art['publisher']}</a>
        </div>

        </div>

        """

    report += """

<hr style="margin-top:20px;border:none;border-top:1px solid #ddd;">

<div style="text-align:center;color:#888;font-size:12px;padding-top:10px;">
Generated by <b>AI News Agent</b> © 2026 <br>
Powered by CrewAI & OpenAI <br>
Created by Suvashis
</div>

</div>
</body>
</html>

"""